# Getting to Know the Data

Question: Are property prices in Mexico more influenced by property size or by location?

In this notebook I load three CSV files, check them for problems, clean them,
combine them into one dataset, and look at the first summary statistics.

In [26]:
# Import pandas for data manipulation
import pandas as pd

## 1. Load the first file

In [27]:
# Define the path to our data file
path_1 = "./data/mexico-real-estate-1.csv"

# Print it to verify
print(f'We will load data from: "{path_1}"')

We will load data from: "./data/mexico-real-estate-1.csv"

In [28]:
# Load the dataset using the variable we defined
(
    pd.read_csv(path_1)
)

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.56,-99.23,150.00,"$67,965.56"
1,house,Nuevo León,25.69,-100.20,186.00,"$63,223.78"
2,apartment,Guerrero,16.77,-99.76,82.00,"$84,298.37"
3,apartment,Guerrero,16.83,-99.91,150.00,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.00,"$94,835.67"
...,...,...,...,...,...,...
695,house,Morelos,NaN,NaN,310.00,"$237,089.17"
696,house,Yucatán,21.05,-89.56,334.00,"$137,017.34"
697,house,Yucatán,21.34,-89.26,130.00,"$110,404.35"
698,apartment,Nuevo León,NaN,NaN,155.00,"$184,446.42"
699,house,Querétaro,20.59,-100.42,106.00,"$56,637.97"

## 2. Inspect the data (five checks)
`.head()`, `.shape`, `.info()`, `.dtypes`, `.isnull().sum()`

In [29]:
# 1. First 5 rows
(
    pd.read_csv(path_1)
    .head()
)

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.56,-99.23,150.00,"$67,965.56"
1,house,Nuevo León,25.69,-100.20,186.00,"$63,223.78"
2,apartment,Guerrero,16.77,-99.76,82.00,"$84,298.37"
3,apartment,Guerrero,16.83,-99.91,150.00,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.00,"$94,835.67"

In [30]:
# 2. Rows and columns
(
    pd.read_csv(path_1)
    .shape
)

(700, 6)

In [31]:
# 3. Column types and non-null counts
(
    pd.read_csv(path_1)
    .info()
)

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  700 non-null    str
 1   state          700 non-null    str
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        700 non-null    float64
 5   price_usd      700 non-null    str
dtypes: float64(3), str(3)
memory usage: 32.9 KB

In [32]:
# 4. Data type of each column
(
    pd.read_csv(path_1)
    .dtypes
)

property_type        str
state                str
lat              float64
lon              float64
area_m2          float64
price_usd            str
dtype: object

In [33]:
# 5. Missing values per column
(
    pd.read_csv(path_1)
    .isnull()
    .sum()
)

property_type      0
state              0
lat              117
lon              117
area_m2            0
price_usd          0
dtype: int64

## 3. Clean file 1
Step 1: drop rows with missing values. Step 2: turn `price_usd` from text into numbers.

In [34]:
# Step 1: Drop missing values
(
    pd.read_csv(path_1)
    .dropna()  # Remove rows where values are missing
)

    property_type             state   lat     lon  area_m2    price_usd
0           house  Estado de México 19.56  -99.23   150.00   $67,965.56
1           house        Nuevo León 25.69 -100.20   186.00   $63,223.78
2       apartment          Guerrero 16.77  -99.76    82.00   $84,298.37
3       apartment          Guerrero 16.83  -99.91   150.00   $94,308.80
5           house           Yucatán 21.05  -89.54   205.00  $105,191.37
..            ...               ...   ...     ...      ...          ...
693         house            Puebla 19.05  -98.28   198.00  $115,910.26
694     apartment  Distrito Federal 19.31  -99.17    70.00   $77,572.89
696         house           Yucatán 21.05  -89.56   334.00  $137,017.34
697         house           Yucatán 21.34  -89.26   130.00  $110,404.35
699         house         Querétaro 20.59 -100.42   106.00   $56,637.97

[583 rows x 6 columns]

In [35]:
# Step 2: The complete chain
(
    pd.read_csv(path_1)
    # 1. Drop rows with missing critical data
    .dropna()

    # 2. Create clean numeric columns using `.assign()`
    # We use 'lambda x' to refer to the data at this specific step in the chain
    # We overwrite 'price_usd' by accessing the current df (x in our lambda function) and cleaning the string
    .assign(
        price_usd = lambda x: x["price_usd"]
                          .str.replace("$", "", regex=False)
                          .str.replace(",", "", regex=False)
                          .astype(float)
    )
)

    property_type             state   lat     lon  area_m2  price_usd
0           house  Estado de México 19.56  -99.23   150.00  67,965.56
1           house        Nuevo León 25.69 -100.20   186.00  63,223.78
2       apartment          Guerrero 16.77  -99.76    82.00  84,298.37
3       apartment          Guerrero 16.83  -99.91   150.00  94,308.80
5           house           Yucatán 21.05  -89.54   205.00 105,191.37
..            ...               ...   ...     ...      ...        ...
693         house            Puebla 19.05  -98.28   198.00 115,910.26
694     apartment  Distrito Federal 19.31  -99.17    70.00  77,572.89
696         house           Yucatán 21.05  -89.56   334.00 137,017.34
697         house           Yucatán 21.34  -89.26   130.00 110,404.35
699         house         Querétaro 20.59 -100.42   106.00  56,637.97

[583 rows x 6 columns]

In [36]:
df1 = (
    pd.read_csv(path_1)
        .dropna()

        .assign(
            price_usd = lambda x: x["price_usd"]
                .str.replace("$", "", regex=False)
                .str.replace(",", "", regex=False)
                .astype(float)
        )
)

## 4. Clean file 2 (prices are in pesos)

In [37]:
# Define the path to our data file
path_2 = "data/mexico-real-estate-2.csv"

In [38]:
# cleaning process using method chaining
df2 = (
    pd.read_csv(path_2)

    # Create "price_usd" column (19 pesos to the dollar in 2014)
    .assign(price_usd = lambda x: x["price_mxn"].div(19))

    # Drop "price_mxn" column
    .drop(columns=["price_mxn"])

    # Drop null values
    .dropna()
)

# Print object type, shape, and head
print(f"df2 type: {type(df2)}")
print(f"df2 shape: {df2.shape}")
df2.head()

df2 type: <class 'pandas.DataFrame'>
df2 shape: (571, 6)

  property_type             state   lat     lon  area_m2  price_usd
0     apartment        Nuevo León 25.72 -100.35    72.00  68,421.05
2         house           Morelos 23.63 -102.55   360.00 278,947.37
6     apartment  Estado de México 19.27  -99.57    85.00  65,789.47
7         house   San Luis Potosí 22.14 -101.00   158.00 111,578.95
8     apartment  Distrito Federal 19.39  -99.13    65.00  39,904.74

## 5. Clean file 3 (messy columns)
`lat-lon` has two values in one cell, and the state is hidden inside `place_with_parent_names`.

In [39]:
# Define the path to our data file
path_3 = "data/mexico-real-estate-3.csv"

In [40]:
(
    pd.read_csv(path_3)
    .head()
)

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.00,"48,550.59"
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.00,"168,636.73"
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.00,"86,932.69"
3,house,|México|Morelos|Temixco|Burgos Bugambilias|,NaN,275.00,"263,432.41"
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.00,"68,508.67"

In [41]:
(
    pd.read_csv(path_3)
    ["lat-lon"]
    .head()
)

0       19.52589,-99.151703
1    19.2640539,-99.5727534
2      19.268629,-99.671722
3                       NaN
4      19.511938,-96.871956
Name: lat-lon, dtype: str

In [42]:
(
    pd.read_csv(path_3)
    ["lat-lon"]
    .str.split(",", expand=True)
    .head()
)

            0            1
0    19.52589   -99.151703
1  19.2640539  -99.5727534
2   19.268629   -99.671722
3         NaN          NaN
4   19.511938   -96.871956

In [43]:
(
    pd.read_csv(path_3)
    ["lat-lon"]
    .str.split(",", expand=True)[0]
    .astype(float)
    .head()
)

0   19.53
1   19.26
2   19.27
3     NaN
4   19.51
Name: 0, dtype: float64

In [44]:
(
    pd.read_csv(path_3)
    ["place_with_parent_names"]
    .head()
)

0    |México|Distrito Federal|Gustavo A. Madero|Acu...
1             |México|Estado de México|Toluca|Metepec|
2    |México|Estado de México|Toluca|Toluca de Lerd...
3          |México|Morelos|Temixco|Burgos Bugambilias|
4    |México|Veracruz de Ignacio de la Llave|Veracruz|
Name: place_with_parent_names, dtype: str

In [45]:
(
    pd.read_csv(path_3)
    ["place_with_parent_names"]
    .str.split("|", expand=True)
    .head()
)

,0,1,2,3,4,5,6
0,,México,Distrito Federal,Gustavo A. Madero,Acueducto de Guadalupe,,NaN
1,,México,Estado de México,Toluca,Metepec,,NaN
2,,México,Estado de México,Toluca,Toluca de Lerdo,Ocho Cedros,
3,,México,Morelos,Temixco,Burgos Bugambilias,,NaN
4,,México,Veracruz de Ignacio de la Llave,Veracruz,,NaN,NaN

In [46]:
# cleaning process using method chaining
df3 = (
    pd.read_csv(path_3)
    # Drop null values from df3
    .dropna()
    # Create "lat" and "lon" columns for df3
    .assign(lat=lambda x: x["lat-lon"]
                .str.split(",", expand=True)[0]
                .astype(float),
            lon=lambda x: x["lat-lon"]
                .str.split(",", expand=True)[1]
                .astype(float),
            # Create "state" column for df3
            state=lambda x: x["place_with_parent_names"]
                .str.split("|", expand=True)[2]
           )

    # Drop "place_with_parent_names" and "lat-lon" from df3
    .drop(columns=["place_with_parent_names", "lat-lon"])
)

# Print object type, shape, and head
print("df3 type:", type(df3))
print("df3 shape:", df3.shape)
df3.head()

df3 type: <class 'pandas.DataFrame'>
df3 shape: (582, 6)

,property_type,area_m2,price_usd,lat,lon,state
0,apartment,71.00,"48,550.59",19.53,-99.15,Distrito Federal
1,house,233.00,"168,636.73",19.26,-99.57,Estado de México
2,house,300.00,"86,932.69",19.27,-99.67,Estado de México
4,apartment,84.00,"68,508.67",19.51,-96.87,Veracruz de Ignacio de la Llave
5,house,175.00,"102,763.00",20.69,-103.37,Jalisco

## 6. Check the three files match, then combine

In [47]:
# Check if all column sets are identical
columns_match = set(df1.columns) == set(df2.columns) == set(df3.columns)

if columns_match:
    print("✅ All DataFrames have the same columns.")
else:
    print("❌ Column mismatch detected!")
    # Optional: See the difference
    print("df1 vs df2 diff:", set(df1.columns) ^ set(df2.columns))
    print("df2 vs df3 diff:", set(df2.columns) ^ set(df3.columns))

✅ All DataFrames have the same columns.

In [48]:
# Stack df1, df2, and df3 vertically
df = pd.concat([df1, df2, df3], ignore_index=True)

# Verify the result
print(f"Combined Shape: {df.shape}")
df.head()

Combined Shape: (1736, 6)

  property_type             state   lat     lon  area_m2  price_usd
0         house  Estado de México 19.56  -99.23   150.00  67,965.56
1         house        Nuevo León 25.69 -100.20   186.00  63,223.78
2     apartment          Guerrero 16.77  -99.76    82.00  84,298.37
3     apartment          Guerrero 16.83  -99.91   150.00  94,308.80
4         house           Yucatán 21.05  -89.54   205.00 105,191.37

In [49]:
# Save your cleaned combined dataset
df.to_csv("./data/mexico-real-estate-combined-clean.csv", index=False)

## 7. Summary statistics

In [50]:
# Summarize the numeric columns
summary = df[["price_usd", "area_m2"]].describe()

# Format for readability
pd.options.display.float_format = '{:,.2f}'.format

summary

       price_usd  area_m2
count   1,736.00 1,736.00
mean  115,331.98   170.26
std    65,426.17    80.59
min    33,157.89    60.00
25%    65,789.47   101.75
50%    99,262.13   156.00
75%   150,846.66   220.00
max   326,733.66   385.00